from __future__ import annotations

# Permission names are stable identifiers used by require_permission("...")

APPROVE_REQUISITION = "APPROVE_REQUISITION"
CONFIRM_REQUISITION = "CONFIRM_REQUISITION"
REVIEW_REQUISITION = "REVIEW_REQUISITION"
CREATE_REQUISITION = "CREATE_REQUISITION"
CREATE_LPO = "CREATE_LPO"
CANCEL_LPO = "CANCEL_LPO"
CREATE_GRN = "CREATE_GRN"
CONFIRM_GRN_STORE = "CONFIRM_GRN_STORE"
CONFIRM_GRN_FINANCE = "CONFIRM_GRN_FINANCE"
CREATE_INVOICE = "CREATE_INVOICE"
CREATE_PAYMENT = "CREATE_PAYMENT"
EVALUATE_INVOICE_MATCH = "EVALUATE_INVOICE_MATCH"
APPROVE_INVOICE_FOR_PAYMENT = "APPROVE_INVOICE_FOR_PAYMENT"
SCHEDULE_PAYMENT = "SCHEDULE_PAYMENT"
MARK_PAYMENT_PAID = "MARK_PAYMENT_PAID"
CANCEL_PAYMENT = "CANCEL_PAYMENT"

CREATE_PETTY_CASH = "CREATE_PETTY_CASH"
CONFIRM_PETTY_CASH = "CONFIRM_PETTY_CASH"

CREATE_SALES = "CREATE_SALES"
VIEW_SALES = "VIEW_SALES"

VIEW_PRICING = "VIEW_PRICING"

VIEW_RBAC = "VIEW_RBAC"
VIEW_INVENTORY = "VIEW_INVENTORY"
CREATE_PORTIONING = "CREATE_PORTIONING"
CONFIRM_PORTIONING = "CONFIRM_PORTIONING"
