"""initial_schema

Revision ID: 47b2e77ec3c0
Revises: 
Create Date: 2026-01-31 07:38:22.028532

"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47b2e77ec3c0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sku', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('unit', sa.String(length=30), nullable=False),
    sa.Column('is_cogs', sa.Boolean(), nullable=False),
    sa.Column('category', sa.String(length=120), nullable=False),
    sa.Column('moq', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sku')
    )
    op.create_index('ix_item_name', 'items', ['name'], unique=False)
    op.create_index('ix_item_sku', 'items', ['sku'], unique=False)
    op.create_table('locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('brand', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('vendors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('phone', sa.String(length=40), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('payment_terms', sa.String(length=50), nullable=False),
    sa.Column('category_tags', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('departments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('location_id', 'name', name='uq_department_location_name')
    )
    op.create_index('ix_departments_location', 'departments', ['location_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_index('ix_users_location', 'users', ['location_id'], unique=False)
    op.create_table('petty_cash_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('txn_date', sa.Date(), nullable=False),
    sa.Column('vendor_name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('method', sa.String(length=40), nullable=False),
    sa.Column('reference', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=False),
    sa.CheckConstraint('amount >= 0', name='ck_petty_amount_ge_zero'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_petty_created_by', 'petty_cash_transactions', ['created_by_user_id'], unique=False)
    op.create_index('ix_petty_location_date', 'petty_cash_transactions', ['location_id', 'txn_date'], unique=False)
    op.create_index('ix_petty_location_status_created_at', 'petty_cash_transactions', ['location_id', 'status', 'created_at'], unique=False)
    op.create_table('requisitions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('requested_by_user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['requested_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_requisitions_created_by', 'requisitions', ['created_by_user_id'], unique=False)
    op.create_index('ix_requisitions_department', 'requisitions', ['department_id'], unique=False)
    op.create_index('ix_requisitions_location_status_created_at', 'requisitions', ['location_id', 'status', 'created_at'], unique=False)
    op.create_table('sales_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('sales_date', sa.Date(), nullable=False),
    sa.Column('department', sa.String(length=120), nullable=False),
    sa.Column('category', sa.String(length=120), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('notes', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=False),
    sa.CheckConstraint('amount >= 0', name='ck_sales_amount_ge_zero'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_sales_created_by', 'sales_records', ['created_by_user_id'], unique=False)
    op.create_index('ix_sales_location_date', 'sales_records', ['location_id', 'sales_date'], unique=False)
    op.create_index('ix_sales_location_status_created_at', 'sales_records', ['location_id', 'status', 'created_at'], unique=False)
    op.create_table('user_roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'role_id', name='uq_user_role')
    )
    op.create_index('ix_user_roles_role', 'user_roles', ['role_id'], unique=False)
    op.create_index('ix_user_roles_user', 'user_roles', ['user_id'], unique=False)
    op.create_table('lpos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('vendor_id', sa.Integer(), nullable=False),
    sa.Column('requisition_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('expected_delivery_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['requisition_id'], ['requisitions.id'], ),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_lpos_created_by', 'lpos', ['created_by_user_id'], unique=False)
    op.create_index('ix_lpos_location_status_created_at', 'lpos', ['location_id', 'status', 'created_at'], unique=False)
    op.create_index('ix_lpos_requisition', 'lpos', ['requisition_id'], unique=False)
    op.create_index('ix_lpos_vendor', 'lpos', ['vendor_id'], unique=False)
    op.create_table('requisition_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('requisition_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=False),
    sa.CheckConstraint('quantity > 0', name='ck_req_line_qty_gt_zero'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.ForeignKeyConstraint(['requisition_id'], ['requisitions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_requisition_lines_item', 'requisition_lines', ['item_id'], unique=False)
    op.create_index('ix_requisition_lines_requisition', 'requisition_lines', ['requisition_id'], unique=False)
    op.create_table('grns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('lpo_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('store_signed_by_user_id', sa.Integer(), nullable=True),
    sa.Column('delivery_signed_by_name', sa.String(length=200), nullable=False),
    sa.Column('finance_signed_by_user_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['finance_signed_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['lpo_id'], ['lpos.id'], ),
    sa.ForeignKeyConstraint(['store_signed_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_grns_created_by', 'grns', ['created_by_user_id'], unique=False)
    op.create_index('ix_grns_location_status_created_at', 'grns', ['location_id', 'status', 'created_at'], unique=False)
    op.create_index('ix_grns_lpo', 'grns', ['lpo_id'], unique=False)
    op.create_table('lpo_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lpo_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('ordered_qty', sa.Float(), nullable=False),
    sa.Column('unit_price', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=False),
    sa.CheckConstraint('ordered_qty > 0', name='ck_lpo_line_ordered_qty_gt_zero'),
    sa.CheckConstraint('unit_price >= 0', name='ck_lpo_line_unit_price_ge_zero'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.ForeignKeyConstraint(['lpo_id'], ['lpos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lpo_id', 'item_id', name='uq_lpo_item')
    )
    op.create_index('ix_lpo_lines_item', 'lpo_lines', ['item_id'], unique=False)
    op.create_index('ix_lpo_lines_lpo', 'lpo_lines', ['lpo_id'], unique=False)
    op.create_table('grn_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('grn_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('received_qty', sa.Float(), nullable=False),
    sa.Column('unit_price', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=False),
    sa.CheckConstraint('received_qty >= 0', name='ck_grn_line_received_qty_ge_zero'),
    sa.CheckConstraint('unit_price >= 0', name='ck_grn_line_unit_price_ge_zero'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['grn_id'], ['grns.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('grn_id', 'item_id', name='uq_grn_item')
    )
    op.create_index('ix_grn_lines_grn', 'grn_lines', ['grn_id'], unique=False)
    op.create_index('ix_grn_lines_item', 'grn_lines', ['item_id'], unique=False)
    op.create_table('inventory_movements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('movement_type', sa.String(length=20), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('unit_cost', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('grn_id', sa.Integer(), nullable=True),
    sa.Column('requisition_id', sa.Integer(), nullable=True),
    sa.Column('source_department_id', sa.Integer(), nullable=True),
    sa.Column('destination_department_id', sa.Integer(), nullable=True),
    sa.Column('batch_ref', sa.String(length=120), nullable=False),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=False),
    sa.CheckConstraint('quantity != 0', name='ck_inv_movement_qty_ne_zero'),
    sa.CheckConstraint('unit_cost >= 0', name='ck_inv_movement_unit_cost_ge_zero'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['destination_department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['grn_id'], ['grns.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['requisition_id'], ['requisitions.id'], ),
    sa.ForeignKeyConstraint(['source_department_id'], ['departments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id', 'location_id', name='uq_inv_movement_location')
    )
    op.create_index('ix_inv_movements_created_by', 'inventory_movements', ['created_by_user_id'], unique=False)
    op.create_index('ix_inv_movements_item', 'inventory_movements', ['item_id'], unique=False)
    op.create_index('ix_inv_movements_location_created_at', 'inventory_movements', ['location_id', 'created_at'], unique=False)
    op.create_index('ix_inv_movements_location_item_created_at', 'inventory_movements', ['location_id', 'item_id', 'created_at'], unique=False)
    op.create_table('invoices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('grn_id', sa.Integer(), nullable=False),
    sa.Column('vendor_invoice_number', sa.String(length=120), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['grn_id'], ['grns.id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_invoices_created_by', 'invoices', ['created_by_user_id'], unique=False)
    op.create_index('ix_invoices_grn', 'invoices', ['grn_id'], unique=False)
    op.create_index('ix_invoices_location_status_created_at', 'invoices', ['location_id', 'status', 'created_at'], unique=False)
    op.create_table('invoice_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('billed_qty', sa.Float(), nullable=False),
    sa.Column('unit_price', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=False),
    sa.CheckConstraint('billed_qty >= 0', name='ck_invoice_line_billed_qty_ge_zero'),
    sa.CheckConstraint('unit_price >= 0', name='ck_invoice_line_unit_price_ge_zero'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('invoice_id', 'item_id', name='uq_invoice_item')
    )
    op.create_index('ix_invoice_lines_invoice', 'invoice_lines', ['invoice_id'], unique=False)
    op.create_index('ix_invoice_lines_item', 'invoice_lines', ['item_id'], unique=False)
    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('method', sa.String(length=40), nullable=False),
    sa.Column('reference', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_payments_created_by', 'payments', ['created_by_user_id'], unique=False)
    op.create_index('ix_payments_invoice', 'payments', ['invoice_id'], unique=False)
    op.create_index('ix_payments_location_status_created_at', 'payments', ['location_id', 'status', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_payments_location_status_created_at', table_name='payments')
    op.drop_index('ix_payments_invoice', table_name='payments')
    op.drop_index('ix_payments_created_by', table_name='payments')
    op.drop_table('payments')
    op.drop_index('ix_invoice_lines_item', table_name='invoice_lines')
    op.drop_index('ix_invoice_lines_invoice', table_name='invoice_lines')
    op.drop_table('invoice_lines')
    op.drop_index('ix_invoices_location_status_created_at', table_name='invoices')
    op.drop_index('ix_invoices_grn', table_name='invoices')
    op.drop_index('ix_invoices_created_by', table_name='invoices')
    op.drop_table('invoices')
    op.drop_index('ix_inv_movements_location_item_created_at', table_name='inventory_movements')
    op.drop_index('ix_inv_movements_location_created_at', table_name='inventory_movements')
    op.drop_index('ix_inv_movements_item', table_name='inventory_movements')
    op.drop_index('ix_inv_movements_created_by', table_name='inventory_movements')
    op.drop_table('inventory_movements')
    op.drop_index('ix_grn_lines_item', table_name='grn_lines')
    op.drop_index('ix_grn_lines_grn', table_name='grn_lines')
    op.drop_table('grn_lines')
    op.drop_index('ix_lpo_lines_lpo', table_name='lpo_lines')
    op.drop_index('ix_lpo_lines_item', table_name='lpo_lines')
    op.drop_table('lpo_lines')
    op.drop_index('ix_grns_lpo', table_name='grns')
    op.drop_index('ix_grns_location_status_created_at', table_name='grns')
    op.drop_index('ix_grns_created_by', table_name='grns')
    op.drop_table('grns')
    op.drop_index('ix_requisition_lines_requisition', table_name='requisition_lines')
    op.drop_index('ix_requisition_lines_item', table_name='requisition_lines')
    op.drop_table('requisition_lines')
    op.drop_index('ix_lpos_vendor', table_name='lpos')
    op.drop_index('ix_lpos_requisition', table_name='lpos')
    op.drop_index('ix_lpos_location_status_created_at', table_name='lpos')
    op.drop_index('ix_lpos_created_by', table_name='lpos')
    op.drop_table('lpos')
    op.drop_index('ix_user_roles_user', table_name='user_roles')
    op.drop_index('ix_user_roles_role', table_name='user_roles')
    op.drop_table('user_roles')
    op.drop_index('ix_sales_location_status_created_at', table_name='sales_records')
    op.drop_index('ix_sales_location_date', table_name='sales_records')
    op.drop_index('ix_sales_created_by', table_name='sales_records')
    op.drop_table('sales_records')
    op.drop_index('ix_requisitions_location_status_created_at', table_name='requisitions')
    op.drop_index('ix_requisitions_department', table_name='requisitions')
    op.drop_index('ix_requisitions_created_by', table_name='requisitions')
    op.drop_table('requisitions')
    op.drop_index('ix_petty_location_status_created_at', table_name='petty_cash_transactions')
    op.drop_index('ix_petty_location_date', table_name='petty_cash_transactions')
    op.drop_index('ix_petty_created_by', table_name='petty_cash_transactions')
    op.drop_table('petty_cash_transactions')
    op.drop_index('ix_users_location', table_name='users')
    op.drop_table('users')
    op.drop_index('ix_departments_location', table_name='departments')
    op.drop_table('departments')
    op.drop_table('vendors')
    op.drop_table('roles')
    op.drop_table('locations')
    op.drop_index('ix_item_sku', table_name='items')
    op.drop_index('ix_item_name', table_name='items')
    op.drop_table('items')
    # ### end Alembic commands ###
