"""phase5_petty_cash_lines

Revision ID: 5c448eddb9ca
Revises: 8bc56412e410
Create Date: 2026-01-31 09:31:15.420789

"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect


# revision identifiers, used by Alembic.
revision = '5c448eddb9ca'
down_revision = '8bc56412e410'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = inspect(bind)

    if not inspector.has_table('petty_cash_lines'):
        op.create_table(
            'petty_cash_lines',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('petty_cash_txn_id', sa.Integer(), nullable=False),
            sa.Column('description', sa.String(length=500), nullable=False),
            sa.Column('item_id', sa.Integer(), nullable=True),
            sa.Column('quantity', sa.Float(), nullable=False),
            sa.Column('unit_price', sa.Float(), nullable=False),
            sa.Column('amount', sa.Float(), nullable=False),
            sa.Column('status', sa.String(length=20), nullable=False),
            sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
            sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
            sa.Column('created_by_user_id', sa.Integer(), nullable=False),
            sa.CheckConstraint('amount >= 0', name='ck_petty_line_amount_ge_zero'),
            sa.CheckConstraint('quantity >= 0', name='ck_petty_line_qty_ge_zero'),
            sa.CheckConstraint('unit_price >= 0', name='ck_petty_line_unit_price_ge_zero'),
            sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id']),
            sa.ForeignKeyConstraint(['item_id'], ['items.id']),
            sa.ForeignKeyConstraint(['petty_cash_txn_id'], ['petty_cash_transactions.id']),
            sa.PrimaryKeyConstraint('id'),
        )

    existing_indexes = {ix.get('name') for ix in inspector.get_indexes('petty_cash_lines')} if inspector.has_table('petty_cash_lines') else set()
    if 'ix_petty_lines_item' not in existing_indexes:
        op.create_index('ix_petty_lines_item', 'petty_cash_lines', ['item_id'], unique=False)
    if 'ix_petty_lines_txn' not in existing_indexes:
        op.create_index('ix_petty_lines_txn', 'petty_cash_lines', ['petty_cash_txn_id'], unique=False)

    with op.batch_alter_table('sales_records', schema=None) as batch_op:
        existing_uqs = {uc.get('name') for uc in inspector.get_unique_constraints('sales_records')}
        if 'uq_sales_location_date_dept_category' not in existing_uqs:
            batch_op.create_unique_constraint(
                'uq_sales_location_date_dept_category',
                ['location_id', 'sales_date', 'department', 'category'],
            )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = inspect(bind)

    with op.batch_alter_table('sales_records', schema=None) as batch_op:
        existing_uqs = {uc.get('name') for uc in inspector.get_unique_constraints('sales_records')}
        if 'uq_sales_location_date_dept_category' in existing_uqs:
            batch_op.drop_constraint('uq_sales_location_date_dept_category', type_='unique')

    if inspector.has_table('petty_cash_lines'):
        existing_indexes = {ix.get('name') for ix in inspector.get_indexes('petty_cash_lines')}
        if 'ix_petty_lines_txn' in existing_indexes:
            op.drop_index('ix_petty_lines_txn', table_name='petty_cash_lines')
        if 'ix_petty_lines_item' in existing_indexes:
            op.drop_index('ix_petty_lines_item', table_name='petty_cash_lines')
        op.drop_table('petty_cash_lines')
    # ### end Alembic commands ###
