"""phase5_finance_invoice_payment

Revision ID: 8bc56412e410
Revises: d3613cfd5100
Create Date: 2026-01-31 09:18:15.903004

"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8bc56412e410'
down_revision = 'd3613cfd5100'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.alter_column(
            'status',
            existing_type=sa.VARCHAR(length=20),
            type_=sa.String(length=30),
            existing_nullable=False,
        )
        batch_op.create_unique_constraint('uq_invoice_grn', ['grn_id'])

    # Data migration: legacy status value -> new state name
    op.execute("UPDATE invoices SET status='DRAFT' WHERE status='PENDING'")

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('amount', sa.Float(), nullable=False, server_default='0'))
        batch_op.create_check_constraint('ck_payment_amount_ge_zero', 'amount >= 0')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_constraint('ck_payment_amount_ge_zero', type_='check')
        batch_op.drop_column('amount')

    op.execute("UPDATE invoices SET status='PENDING' WHERE status='DRAFT'")

    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.drop_constraint('uq_invoice_grn', type_='unique')
        batch_op.alter_column(
            'status',
            existing_type=sa.String(length=30),
            type_=sa.VARCHAR(length=20),
            existing_nullable=False,
        )
    # ### end Alembic commands ###
