"""phase4_inventory_source_doc

Revision ID: b3c4a950c834
Revises: 8a4346e610b4
Create Date: 2026-01-31 08:47:59.885669

"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3c4a950c834'
down_revision = '8a4346e610b4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'inventory_movements',
        sa.Column('source_document_type', sa.String(length=40), nullable=False, server_default=''),
    )
    op.add_column('inventory_movements', sa.Column('source_document_id', sa.Integer(), nullable=True))
    op.create_index('ix_inv_movements_source_doc', 'inventory_movements', ['source_document_type', 'source_document_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_inv_movements_source_doc', table_name='inventory_movements')
    op.drop_column('inventory_movements', 'source_document_id')
    op.drop_column('inventory_movements', 'source_document_type')
    # ### end Alembic commands ###
