"""phase4_portioning

Revision ID: d3613cfd5100
Revises: b3c4a950c834
Create Date: 2026-01-31 08:54:53.244661

"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3613cfd5100'
down_revision = 'b3c4a950c834'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('portioning_batches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_portioning_batches_created_by', 'portioning_batches', ['created_by_user_id'], unique=False)
    op.create_index('ix_portioning_batches_location_status_created_at', 'portioning_batches', ['location_id', 'status', 'created_at'], unique=False)
    op.create_table('portioning_input_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=False),
    sa.CheckConstraint('quantity > 0', name='ck_portioning_input_qty_gt_zero'),
    sa.ForeignKeyConstraint(['batch_id'], ['portioning_batches.id'], ),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_portioning_input_lines_batch', 'portioning_input_lines', ['batch_id'], unique=False)
    op.create_index('ix_portioning_input_lines_item', 'portioning_input_lines', ['item_id'], unique=False)
    op.create_table('portioning_loss_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=False),
    sa.CheckConstraint('quantity > 0', name='ck_portioning_loss_qty_gt_zero'),
    sa.ForeignKeyConstraint(['batch_id'], ['portioning_batches.id'], ),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_portioning_loss_lines_batch', 'portioning_loss_lines', ['batch_id'], unique=False)
    op.create_index('ix_portioning_loss_lines_item', 'portioning_loss_lines', ['item_id'], unique=False)
    op.create_table('portioning_output_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=False),
    sa.CheckConstraint('quantity > 0', name='ck_portioning_output_qty_gt_zero'),
    sa.ForeignKeyConstraint(['batch_id'], ['portioning_batches.id'], ),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_portioning_output_lines_batch', 'portioning_output_lines', ['batch_id'], unique=False)
    op.create_index('ix_portioning_output_lines_item', 'portioning_output_lines', ['item_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_portioning_output_lines_item', table_name='portioning_output_lines')
    op.drop_index('ix_portioning_output_lines_batch', table_name='portioning_output_lines')
    op.drop_table('portioning_output_lines')
    op.drop_index('ix_portioning_loss_lines_item', table_name='portioning_loss_lines')
    op.drop_index('ix_portioning_loss_lines_batch', table_name='portioning_loss_lines')
    op.drop_table('portioning_loss_lines')
    op.drop_index('ix_portioning_input_lines_item', table_name='portioning_input_lines')
    op.drop_index('ix_portioning_input_lines_batch', table_name='portioning_input_lines')
    op.drop_table('portioning_input_lines')
    op.drop_index('ix_portioning_batches_location_status_created_at', table_name='portioning_batches')
    op.drop_index('ix_portioning_batches_created_by', table_name='portioning_batches')
    op.drop_table('portioning_batches')
    # ### end Alembic commands ###
